//! Autogenerated weights for pallet_identity_registry
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: (placeholder)
//!
//! NOTE: This is a placeholder file. Run benchmarks to generate actual weights.

use frame_support::weights::Weight;

pub trait WeightInfo {
	fn register_identity() -> Weight;
	fn update_jurisdiction() -> Weight;
	fn verify_identity() -> Weight;
}

/// Placeholder weights
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_identity() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}

	fn update_jurisdiction() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}

	fn verify_identity() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
}

impl WeightInfo for () {
	fn register_identity() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}

	fn update_jurisdiction() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}

	fn verify_identity() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
}
