//! Autogenerated weights for pallet_consent_manager
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: (placeholder)
//!
//! NOTE: This is a placeholder file. Run benchmarks to generate actual weights.

use frame_support::weights::Weight;

pub trait WeightInfo {
	fn grant_consent() -> Weight;
	fn revoke_consent() -> Weight;
	fn update_consent() -> Weight;
	fn check_consent_validity() -> Weight;
}

/// Placeholder weights
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn grant_consent() -> Weight {
		Weight::from_parts(80_000_000, 0)
	}

	fn revoke_consent() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}

	fn update_consent() -> Weight {
		Weight::from_parts(60_000_000, 0)
	}

	fn check_consent_validity() -> Weight {
		Weight::from_parts(70_000_000, 0)
	}
}

impl WeightInfo for () {
	fn grant_consent() -> Weight {
		Weight::from_parts(80_000_000, 0)
	}

	fn revoke_consent() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}

	fn update_consent() -> Weight {
		Weight::from_parts(60_000_000, 0)
	}

	fn check_consent_validity() -> Weight {
		Weight::from_parts(70_000_000, 0)
	}
}
