//! Autogenerated weights for pallet_authentication
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: (placeholder)
//!
//! NOTE: This is a placeholder file. Run benchmarks to generate actual weights.

use frame_support::weights::Weight;

pub trait WeightInfo {
	fn assign_role() -> Weight;
	fn revoke_role() -> Weight;
	fn create_session() -> Weight;
	fn end_session() -> Weight;
	fn check_permission() -> Weight;
}

/// Placeholder weights
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn assign_role() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}

	fn revoke_role() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}

	fn create_session() -> Weight {
		Weight::from_parts(60_000_000, 0)
	}

	fn end_session() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}

	fn check_permission() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
}

impl WeightInfo for () {
	fn assign_role() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}

	fn revoke_role() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}

	fn create_session() -> Weight {
		Weight::from_parts(60_000_000, 0)
	}

	fn end_session() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}

	fn check_permission() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
}
